"""Write models/vr/weapons.txt from the installed cards.

THE MISSING LINK, and the reason no weapon part could be grabbed.

There are two readers of a weapon's parts and they were reading different files:

  - The GAME DLL parses <gamedir>/vr/cards/<model>.card with the full grammar -
    match, type, joint, catch, point, grab, control - and builds the simulator
    from it. This worked; the log says so, one "bound to its card" line per
    weapon.
  - The RENDERER (ref/gl/gl_studio.c, R_StudioLoadCards) reads a completely
    different file, models/vr/weapons.txt, in a much smaller format - weapon /
    action / part - and publishes the bones it names as grabbable parts. That
    file did not exist, so the renderer fell back to the r_vr_action_bone cvar:
    a hand-written list naming ONE OR TWO bones per weapon, written before cards
    existed.

So the simulator had a pistol with two joints while the renderer published one
part, and the slide the player reached for was not a part at all.

This writes the renderer's file from the same cards the game DLL reads, so the
two agree by construction.

ORDER MATTERS AND IS NOT COSMETIC. vrcmd_t.part_value[i] is handed to the
simulator as joint i (VRGun_FromCmd), so the renderer's part index must equal
the card's joint index. Joints are emitted in their declared order, with no
gaps, or the hand drives the wrong part.

    python make_weapons_txt.py <install-root>
"""
import glob
import os
import re
import sys

JOINT = re.compile(r'^\s*joint\s+(\d+)\s+bone\s+"([^"]+)"', re.M)
WEAPON = re.compile(r'^\s*weapon\s+(\S+)', re.M)


def joints_of(path):
    """(model name, [(index, bone), ...]) from a card, in declared order."""
    txt = open(path, encoding='utf-8', errors='ignore').read()
    m = WEAPON.search(txt)
    name = m.group(1) if m else os.path.splitext(os.path.basename(path))[0]
    js = [(int(i), b) for i, b in JOINT.findall(txt)]
    js.sort(key=lambda x: x[0])
    return name, js


def main(argv):
    if not argv:
        print(__doc__)
        return 2

    root = os.path.abspath(argv[0])
    if not os.path.isdir(root):
        print('not a directory: %s' % root)
        return 2

    wrote = 0
    for gamedir in sorted(os.listdir(root)):
        cdir = os.path.join(root, gamedir, 'vr', 'cards')
        if not os.path.isdir(cdir):
            continue

        lines = [
            '// Generated by tools/vrcard/make_weapons_txt.py - do not hand-edit.',
            '//',
            '// The renderer reads this to know which bones are grabbable parts. It is',
            '// generated from the cards in ../cards so the renderer and the game DLL',
            '// cannot disagree about what a weapon is made of. Joint order is the card\'s',
            '// order, because part index IS joint index on the wire.',
            '',
        ]

        n = 0
        gaps = []
        for card in sorted(glob.glob(os.path.join(cdir, '*.card'))):
            name, js = joints_of(card)
            if not js:
                continue

            # A gap in the numbering would slide every later joint onto the wrong
            # part, so it is reported rather than silently closed up.
            expected = list(range(len(js)))
            if [i for i, _ in js] != expected:
                gaps.append('%s: joints numbered %s, expected %s'
                            % (os.path.basename(card), [i for i, _ in js], expected))

            lines.append('weapon %s' % name)
            for idx, bone in js:
                # Joint 0 is the action in every preset that has one - the slide,
                # the pump, the bolt, the cylinder. The renderer marks it with a
                # star and treats it as the part a stroke works.
                lines.append('%-7s%s' % ('action' if idx == 0 else 'part', bone))
            lines.append('')
            n += 1

        if not n:
            continue

        out = os.path.join(root, gamedir, 'models', 'vr')
        os.makedirs(out, exist_ok=True)
        dest = os.path.join(out, 'weapons.txt')
        open(dest, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines))
        print('%s: %d weapons -> %s' % (gamedir, n, dest))
        for g in gaps:
            print('   !! %s' % g)
        wrote += 1

    if not wrote:
        print('no gamedir under %s has installed cards' % root)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
